#!/usr/bin/perl
use 5.010;
use strict;
use warnings;
my $lib_path=`echo $0 | sed "s/\$(basename $0)//g"`;
chomp($lib_path);
require("$lib_path/common.pl");

#cmd vars
my $CAT="/bin/cat";
my $SSH="/usr/bin/ssh";
my $TOUCH="/bin/touch";
my $RM="/bin/rm";
my $MKDIR="/bin/mkdir -p";
my $SCP="/usr/bin/scp";
my $PWD="/bin/pwd";
my $NSLOOKUP="/usr/bin/nslookup";
my $CP="/bin/cp";

#remote file vars
my $remote_keepalived_config="/usr/local/etc/keepalived/keepalived.conf";
my $remote_keepalived_backupfile="/usr/local/etc/keepalived/keepalived.confback";
my $remote_cmd_dir="/home/lvsmonitor/lvs-node/";
my $remote_vip_admin=$remote_cmd_dir."vip_admin.pl";
my $remote_get_rs=$remote_cmd_dir."get_rs.pl";
my $remote_get_allvs=$remote_cmd_dir."get_allvs.pl";
my $remote_reloade_keepalived=$remote_cmd_dir."reload_keepalived.pl";
my $remote_back_config=$remote_cmd_dir."back_config.pl";

#global vars
my $lvs_name;
my $local_config_modified=1;
my $action;
my @args;

#local temp config file vars
#file download from the remote lvs node
my $local_config="keepalived.conf";		
#file download from the remote lvs node and we changed something
my $local_modified_config="modified_keepalived.conf"; 	
my $LOG;

my %tcp_check;
my %misc_check;
my %http_get;
my %ssl_get;

my %err_info=(
	211=>"cat file failed",
	212=>"lvs ip resolv error",
	213=>"touch log file failed",
	214=>"get time error",
	215=>"get_vs failed",
	216=>"no match",
	217=>"ip format is wrong",
	218=>"port format is wrong",
	219=>"please give rs ip",
	220=>"number of args is not currect",
	221=>"args name is wrong",
	222=>"reload_keepalived failed",
	223=>"command(first arg) is not supported",
	224=>"download keepalived config file failed",
	225=>"write @ to file failed",
	226=>"local modified keepalived config file doesn't exit",
	227=>"upload_conf failed",
	228=>"touch modified_keepalived file failed",
	229=>"backup remote lvs config file failed",
	230=>"keepalived config file rollback failed",
	231=>"local config has not modified,won't upload",
	232=>"remove local config failed",
	233=>"local config doesn't exit",
	234=>"touch local_modified_config failed",
	235=>"vs already exit in the config file",
	236=>"vs hasn't been configed in the config file",
	);



my %action=(
	"add_vs"=>\&add_vs,		
	"add_rs"=>\&add_rs,		
	"del_vs"=>\&del_vs,		
	"del_rs"=>\&del_rs,		
	"add_vip"=>\&add_vip,		
	"del_vip"=>\&del_vip,		
	"get_vs"=>\&get_vs, 		
	"get_rs"=>\&get_rs,			
	"download"=>\&download_conf,
	"upload"=>\&upload_conf,
	"backup"=>\&backup_conf,
	"reload"=>\&reload_keepalived,
	"rollback"=>\&rollback,
	"check_vs"=>\&check_vs,
	"check_rs"=>\&check_rs,
	);



my %keepalived_check=(
	"TCP_CHECK"=>\%tcp_check,
	"MISC_CHECK"=>\%misc_check,
	"HTTP_GET"=>\%http_get,
	"SSL_GET"=>\%ssl_get,
	);




sub get_vs(@){
	if($#_ >1){err_exit($err_info{220},220)}
	if(defined $_[0]){
		if(!is_ip($_[0])){err_exit($err_info{217},217)}
	}
	if(defined $_[1]){
		if(!is_port($_[1])){err_exit($err_info{218},218)}
	}
	my $args=join " ",@_;
	my @ret=`$SSH $lvs_name sudo $remote_get_allvs $args`;
	write_log("cmd:$SSH $lvs_name sudo $remote_get_allvs $args");
	if(catch_pattern("success",@ret)){
		write_log("result:success\n");
		say @ret;
	}elsif(catch_pattern("no match",@ret)){
		write_log("result:no match\n");
		err_exit($err_info{216},216);
	}
	else{
		write_log("result:$err_info{215}\n");
		err_exit($err_info{215},215);
	}
}


sub get_rs(@){
	if($#_ > 0){err_exit($err_info{220},220)}
	if(not defined $_[0]){
		err_exit($err_info{219},219)
	}elsif(!is_ip($_[0])){
		err_exit($err_info{217},217);
	}
	my $args=$_[0];
	my @ret=`$SSH $lvs_name sudo $remote_get_rs $args`;
	write_log("cmd:$SSH $lvs_name sudo $remote_get_rs $args");
	if(catch_pattern("success",@ret)){
		write_log("result:success\n");
		say @ret;
	}elsif(catch_pattern("no match",@ret)){
		write_log("result:no match\n");
		err_exit($err_info{216},216);
	}
	else{
		write_log("result:$err_info{215}\n");
		err_exit($err_info{215},215);
	}
}


sub add_vip{
	#add a vip on the lo of the 
	#remote lvs node
	if($#_ ne 0){err_exit($err_info{221},221)}
	my $vip=shift @_;
	if(!is_ip($vip)){
		err_exit($err_info{217},217);
	}
	my @ret=`$SSH $lvs_name sudo $remote_vip_admin add $vip`;
	write_log("cmd:$SSH $lvs_name sudo $remote_vip_admin add $vip");
	write_log("result:@ret");
	say @ret;
}


sub del_vip{
	#del a vip on the lo of the
	#remote lvs node
	if($#_ ne 0){err_exit($err_info{221},221)}
	my $vip=shift @_;
	if(!is_ip($vip)){
		err_exit($err_info{217},217);
	}
	my @ret=`$SSH $lvs_name sudo $remote_vip_admin del $vip`;
	write_log("cmd:$SSH $lvs_name sudo $remote_vip_admin del $vip");
	write_log("result:@ret");
	say @ret;
}


sub download_conf{

	if($#_ > -1){err_exit($err_info{220},200)}
	if(-f "*.conf"){
		my $rem=`$RM *.conf`;
		if($? ne 0){
			err_exit($err_info{232},232);
		}
	}
	`$SCP $lvs_name:$remote_keepalived_config $local_config`;
	if($? ne 0){
		err_exit(err_info{224},224);
	}
	write_log("$SCP $lvs_name:$remote_keepalived_config $local_config");
	if($? ne 0){
		write_log($err_info{224});
		err_exit($err_info{224},224);
	}
	say "download keepalived config file success";
	#write a download time in the config file;
	my $time=get_time();
	my @ret=`$CAT $local_config`;
	if(!check_up_time($time,@ret)){
		@ret=("!time:".$time."-download",@ret);
	}
	write_info($local_config,@ret);
	write_log("download keepalived config file success");
	backup_conf_local();

}



sub upload_conf($$){
	#upload the config file we changed local 
	#up to the remote lvs node
	#every time before we upload the config 
	#we will backup on hte remote lvs node

	#backup_conf
	if($local_config_modified != 1){
		write_log($err_info{231});
		err_exit($err_info{231},231);
	}

	backup_conf();

	if(!-f $local_modified_config){
		err_exit($err_info{226},226);
	}
	my @ret=`$CAT $local_modified_config`;
	my $time=get_time();
	for(@ret){
		#remove the download time infor mation 
		s/!time:[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{2}:[0-9]{2}:[0-9]{2}--download/!time:$time-upload/;
	}
	#if(!-f $local_modified_config){
	#	`$TOUCH $local_modified_config`;
	#	if($? ne 0){
	#		err_exit(err_info{228},228);
	#	}
	#}
	write_info($local_modified_config,@ret);
	`$SCP $local_modified_config $lvs_name:$remote_keepalived_config`;
	if($? ne 0){
		write_log($err_info{227});
		err_exit($err_info{227},227);
	}
	say "upload_conf success";
	write_log("upload_conf success");

}

sub backup_conf_local{
	if($#_ > -1){
		err_exit($err_info{220},220);
	}
	if(!-f $local_config){
		err_exit(err_info{233},233);
	}
	`$CP $local_config $local_modified_config`;
	if($? ne 0){
		write_log("$CP $local_config $local_modified_config");
		err_exit("backup_conf local failed");
	}
	write_log("backup_conf local success");
	say "backup_conf local success";


}

sub backup_conf{
	#backup the keepalived config file on  
	#on the remote lvs node
	#we will add the backup time information 
	#in the keepalived file
	if($#_ > -1){
		err_exit($err_info{220},220);
	}
	my $info="$SSH $lvs_name sudo $remote_back_config";
	write_log($info);
	`$SSH $lvs_name sudo $remote_back_config`;
	if($? ne 0){
		write_log("result:$err_info{229}");
		err_exit($err_info{229},229);
	}else{
		write_log("backup remote success~~");
		say "backup remote success~~~";
	}
}	



sub rollback{
	#rollback the lastest keepalived cnfig file
	#to use
	if($#_ > -1){
		err_exit($err_info{220},220);
	}
	my $info=`$SSH $lvs_name sudo $SCP $remote_keepalived_backupfile $remote_keepalived_config`;
	write_log($info);
	if($? ne 0){
		write_log("result:rollback remote keepalived config failed");
		err_exit($err_info{230},230);
	}
	say "rollback remote keepalived config file success";
	write_log("rollback remote keepalived config file success");
	#after rollback reload the keepalived 
	reload_keepalived();
}




sub reload_keepalived{
	my $args=join " ",@_;
	if($#_ ne 0 and $#_ ne -1){err_exit($err_info{220},220)}
	if(defined $_[0]){
		if($_[0] ne "vrrp" and $_[0] ne "check"){
			err_exit($err_info{221},221);
		}
	}
	my @ret=`$SSH $lvs_name sudo $remote_reloade_keepalived $args`;
	write_log("cmd:$SSH $lvs_name sudo remote_reloade_keepalived $args");
	if(catch_pattern("success",@ret)){
		write_log("result:success\n");
		say @ret;
	}
	else{
		write_log("result:$err_info{222}\n");
		err_exit($err_info{222},222);
	}

}


sub exec_action{
	my $action=shift @_;
	my @args=@_;
	if(!$action{$action}){
		err_exit($err_info{223},223);
	}else{
		$action{$action}(@args);
	}	
}


sub load_local_config($){
	my @ret=`$CAT $_[0]`;
	if($! ne 0){
		err_exit(err_info{211},211);
	}
	else{
		return @ret;
	}
}




sub check_up_time($@){
	my $time=shift @_;
	for(@_){
		if($_=~/!time:[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{2}:[0-9]{2}:[0-9]{2}--upload/){
			s/!time:[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{2}:[0-9]{2}:[0-9]{2}--upload/!time:$time-download/;
			return 1;
		}
	}
	return 0;
}



#sub add_vs{
#	if($#_ ne 2){
#		err_exit($err_info{220},220);
#	}
#	my($vip,$vport,$pro)=@_;
#	if(check_vs($vip,$vport,$port)){
#		write_log($err_info{235}."vip=$vip vport=$vport pro=$pro");
#		err_exit($err_info{235},235);
#	}
#	
#
#}


#sub del_vs($$$){
#	if($#_ ne 2){
#		err_exit($err_info{220},220);
#	}
#	my($vip,$vport,$pro)=@_;
#	if(!check_vs($vip,$vport,$port)){
#		write_log($err_info{236}."vip=$vip vport=$vport pro=$pro vip=$vip vport=$vport");
#		err_exit($err_info{236},236);
#	}
#
#}

sub check_vs{
	if($#_ ne 2){
		err_exit($err_info{220},220);
	}
	my ($vip,$vport,$pro)=@_;
	if(!is_ip($vip) or !is_port($vport) or !is_pro($pro)){
		err_exit("vs args is not currect",0);
	}
	#check conf in file modified_local_config
	if(!-f $local_modified_config){
		write_log("$local_modified_config no exit,download before check");
		download_conf();
	}
	my @ret=`$CAT $local_modified_config`;
	if($? ne 0){
		err_exit($err_info{211},211);
	}
	write_log("check_vs $vip $vport $pro");
	my $match_flag=0;
	for(@ret){
		if($_=~/virtual_server/){
			$match_flag=0;
			if($_=~/virtual_server\s+$vip\s+$vport/){
				$match_flag=1;
			}
		}
		if($_=~/protocol.*$pro/){
				if($match_flag == 1){
					return 1;
				}
		}
	}
	return 0;

}

sub check_rs{
	if($#_ ne 4){
		err_exit($err_info{220},220);
	}
	my($vip,$vport,$pro,$rip,$rport)=@_;
	if(!is_ip($vip) or !is_ip($rip) or !is_port($vport) or !is_port($rport) or !is_pro($pro)){
		err_exit("vs-rs args is not currect",0);
	}
	#check conf in file modified_local_config
	if(!-f $local_modified_config){
		write_log("$local_modified_config no exit,download before check");
		download_conf();
	}
	my @ret=`$CAT $local_modified_config`;
	if($? ne 0){
		err_exit($err_info{211},211);
	}
	my $match_flag1=0;
	my $match_flag2=0;
	for(@ret){
		if($_=~/virtual_server/){
			$match_flag1=0;
			if($_=~/virtual_server\s+$vip\s+$vport/){
				$match_flag1=1;
			}
		}
		if($_=~/protocol.*$pro/){
			if($match_flag1==1){
				$match_flag2=1;
			}
		}
		if($_=~/real_server\s+$rip\s+$rport/){
			if($match_flag1==1 and $match_flag2==1){
				return 1
			}
		}
	}
	return 0;
}



sub edit_vs{

}

sub add_rs{

}


sub del_rs{

}





sub catch_pattern($@){
	my $pattern=shift @_;
	my @str=@_;
	for(@str){
		if($_=~/$pattern/){
			return 1;
		}
	}
	return 0;
}


sub check_lvs_ip($){
	#this function will resolve the ip of 
	#the lvs server
	my @ret=`$NSLOOKUP $_[0]`;
	for(@ret){
		if($_=~/answer/){return 1}
	}
	return 0;
}


sub write_info($@){
	#write a list to a file
	my $file=shift @_;
	my @infos=@_;
	open(F,">$file");
	for(@infos){
		chomp($_);
		say F $_;
	}
}

sub write_log($){
    #write a log for every operator command
    open(LOG,">>$LOG");
   #if($! ne 0){
   #	err_exit("open file log failed",0);
   #}
    my $time=get_time();
    my $info=$_[0];
    $info=$time.$info;
    say LOG $info;
    close(LOG);

}


sub init_env{
	#init nessory env args
	my $ret=`$PWD`;
	my @ret=split /\//,$ret;
	$lvs_name=$ret[$#ret];
	chomp($lvs_name);
	if(!is_ip($lvs_name)){
		err_exit($err_info{212},212);
	}
	#if(!check_lvs_ip($lvs_name)){
	#	err_exit(err_info{212},212);
	#}
	if( !-f 'log'){
		`$TOUCH log`;
		if($! ne 0){err_exit($err_info{213},213)}
	}
	$LOG="log";
}


sub check_argv{
	if($#ARGV < 0 or $ARGV[0] eq "help"){usage($0)}
	$action=shift @ARGV;
	@args=@ARGV;
	if(@args){
		for(@args){
			s/\w+=//;
		}
	}
}


##########main
check_argv();
init_env();
#exec_action(@ARGV)
#get_vs(@args)
exec_action($action,@args);






